# Generated by Django 5.1.4 on 2024-12-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaivariety_delete_chaivarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='discription',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='price',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
