# Generated by Django 5.1.4 on 2024-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaireview',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Very Good'), (2, 'Good'), (3, 'Not Bad'), (4, 'Bad'), (5, 'Poor')]),
        ),
    ]
